#!/usr/bin/env python3
"""Calibrate LLT split-gate thresholds from repeated production runs."""

from __future__ import annotations

import argparse
import json
import os
import statistics
import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def run_cmd(cmd: list[str], cwd: Path, env: dict[str, str]) -> tuple[int, str, str]:
    proc = subprocess.run(cmd, cwd=str(cwd), capture_output=True, text=True, env=env)
    return proc.returncode, proc.stdout, proc.stderr


def load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
        return payload if isinstance(payload, dict) else {}
    except Exception:
        return {}


def as_float(value: Any) -> float | None:
    try:
        return float(value)
    except Exception:
        return None


def summarize(values: list[float], margin: float) -> dict[str, Any]:
    if not values:
        return {
            "count": 0,
            "min": None,
            "max": None,
            "mean": None,
            "recommended_floor": None,
        }
    min_v = min(values)
    return {
        "count": len(values),
        "min": min_v,
        "max": max(values),
        "mean": statistics.fmean(values),
        "recommended_floor": max(0.0, min_v - margin),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Calibrate LLT split thresholds from repeated runs")
    parser.add_argument("--runs", type=int, default=5, help="Number of production-check runs.")
    parser.add_argument("--margin", type=float, default=0.01, help="Safety margin subtracted from observed min.")
    parser.add_argument(
        "--report-path",
        type=Path,
        default=Path("/Users/coo-koba42/dev/tent_io/harness/reports/full_stage_pipeline.current.json"),
        help="Pipeline report generated by production_check.sh.",
    )
    parser.add_argument(
        "--out-json",
        type=Path,
        default=Path("/Users/coo-koba42/dev/tent_io/harness/reports/llt_split_gate_calibration.current.json"),
        help="Calibration JSON output.",
    )
    parser.add_argument(
        "--out-md",
        type=Path,
        default=Path("/Users/coo-koba42/dev/tent_io/harness/reports/llt_split_gate_calibration.current.md"),
        help="Calibration markdown output.",
    )
    args = parser.parse_args()

    if args.runs < 1:
        raise SystemExit("--runs must be >= 1")
    if args.margin < 0:
        raise SystemExit("--margin must be >= 0")

    root = Path("/Users/coo-koba42/dev")
    prod_cmd = ["bash", "tent_io/harness/production_check.sh"]
    env = dict(os.environ)
    # Ensure split gates are off while observing baseline behavior.
    env.update(
        {
            "LLT_MIN_MMLU_TEST_ACC": "-1",
            "LLT_MIN_CONVERSATIONAL_TEST_ACC": "-1",
            "LLT_MIN_EVAL_MMLU_ACC": "-1",
            "LLT_MIN_EVAL_CONVERSATIONAL_ACC": "-1",
        }
    )

    train_mmlu: list[float] = []
    train_conv: list[float] = []
    eval_mmlu: list[float] = []
    eval_conv: list[float] = []
    run_logs: list[dict[str, Any]] = []

    for i in range(1, args.runs + 1):
        rc, out, err = run_cmd(prod_cmd, cwd=root, env=env)
        report = load_json(args.report_path)
        stages = report.get("stages") if isinstance(report.get("stages"), dict) else {}
        train_stage = stages.get("train_liquid_language_model") if isinstance(stages, dict) else {}
        eval_stage = stages.get("eval_liquid_language_model_best") if isinstance(stages, dict) else {}
        train_gates = train_stage.get("gates") if isinstance(train_stage, dict) and isinstance(train_stage.get("gates"), dict) else {}
        eval_gates = eval_stage.get("gates") if isinstance(eval_stage, dict) and isinstance(eval_stage.get("gates"), dict) else {}

        tr_m = as_float(train_gates.get("final_mmlu_test_acc")) if isinstance(train_gates, dict) else None
        tr_c = as_float(train_gates.get("final_conversational_logic_test_acc")) if isinstance(train_gates, dict) else None
        ev_m = as_float(eval_gates.get("mmlu_test_acc")) if isinstance(eval_gates, dict) else None
        ev_c = as_float(eval_gates.get("conversational_logic_test_acc")) if isinstance(eval_gates, dict) else None

        if tr_m is not None:
            train_mmlu.append(tr_m)
        if tr_c is not None:
            train_conv.append(tr_c)
        if ev_m is not None:
            eval_mmlu.append(ev_m)
        if ev_c is not None:
            eval_conv.append(ev_c)

        run_logs.append(
            {
                "run_index": i,
                "rc": rc,
                "status": report.get("status"),
                "train_mmlu": tr_m,
                "train_conversational": tr_c,
                "eval_mmlu": ev_m,
                "eval_conversational": ev_c,
                "stdout_tail": out[-300:],
                "stderr_tail": err[-300:],
            }
        )
        if rc != 0:
            break

    train_mmlu_s = summarize(train_mmlu, args.margin)
    train_conv_s = summarize(train_conv, args.margin)
    eval_mmlu_s = summarize(eval_mmlu, args.margin)
    eval_conv_s = summarize(eval_conv, args.margin)

    recommended_env = {
        "LLT_MIN_MMLU_TEST_ACC": train_mmlu_s["recommended_floor"],
        "LLT_MIN_CONVERSATIONAL_TEST_ACC": train_conv_s["recommended_floor"],
        "LLT_MIN_EVAL_MMLU_ACC": eval_mmlu_s["recommended_floor"],
        "LLT_MIN_EVAL_CONVERSATIONAL_ACC": eval_conv_s["recommended_floor"],
    }
    shell_export = " ".join(
        f'{k}="{v}"' for k, v in recommended_env.items() if isinstance(v, (int, float))
    )

    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    payload: dict[str, Any] = {
        "timestamp_utc": now,
        "runs_requested": args.runs,
        "runs_completed": len(run_logs),
        "margin": args.margin,
        "status": "ok" if run_logs and run_logs[-1].get("rc") == 0 else "partial_or_failed",
        "train_mmlu": train_mmlu_s,
        "train_conversational": train_conv_s,
        "eval_mmlu": eval_mmlu_s,
        "eval_conversational": eval_conv_s,
        "recommended_env": recommended_env,
        "recommended_export": shell_export,
        "runs": run_logs,
    }

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    with args.out_json.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=True)

    lines = [
        "# LLT Split Gate Calibration",
        "",
        f"- timestamp_utc: `{now}`",
        f"- runs_requested: `{args.runs}`",
        f"- runs_completed: `{len(run_logs)}`",
        f"- margin: `{args.margin}`",
        f"- status: `{payload['status']}`",
        "",
        "## Recommended Floors",
        "",
        f"- train_mmlu: `{train_mmlu_s['recommended_floor']}`",
        f"- train_conversational: `{train_conv_s['recommended_floor']}`",
        f"- eval_mmlu: `{eval_mmlu_s['recommended_floor']}`",
        f"- eval_conversational: `{eval_conv_s['recommended_floor']}`",
        "",
        "```bash",
        shell_export + " bash tent_io/harness/production_check.sh",
        "```",
    ]
    with args.out_md.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(
        json.dumps(
            {
                "status": payload["status"],
                "out_json": str(args.out_json),
                "out_md": str(args.out_md),
                "runs_completed": len(run_logs),
            },
            ensure_ascii=True,
            indent=2,
        )
    )
    return 0 if payload["status"] == "ok" else 1


if __name__ == "__main__":
    raise SystemExit(main())
